//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace regestraionandlogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_s_Percent
    {
        public int UserID { get; set; }
        public string StockName { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> Price_Quantity { get; set; }
    }
}
